[package]
name = "properties-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
log4rs = "1.3.0"
serde_yaml = "0.9.34"
serde = { version = "1.0.219", features = ["derive"] }
walkdir = "2.5.0"
